spring.application.name=filemanager
spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

spring.thymeleaf.cache=false

app.security.username=admin
app.security.password=P@ssw0rd123
jwt.secret=HcTSI0thd65AlloXhdtLinelbDzozov92+VbB12rMII=
jwt.expiration=3600000

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=file:U:/project/filemanager.p12
server.ssl.key-store-password=P@ssw0rd
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=filemanager